import HeroHeading from '@/components/HeroHeading';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'FAQ - Shoolin Construction',
	description: 'Generated by create next app',
	alternates: {
		canonical: '/faq',
	},
};

const FaqPage = (): JSX.Element => {
	return (
		<main className="mt-[7rem] h-auto w-full">
			<HeroHeading heading={'FAQ'} subHeading="Frequently Ask Question" />
		</main>
	);
};

export default FaqPage;
