import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'About - Shoolin Construction',
	description: 'Generated by create next app',
};

const AboutLayout = ({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element => {
	return <section>{children}</section>;
};

export default AboutLayout;
