import FAQ from '@/components/FAQ';
import HeroHeading from '@/components/HeroHeading';
import HeroSection from '@/app/about/components/HeroSection';
import OurServicesSection from '@/app/about/components/OurServicesSection';
import OurTeamSection from '@/app/about/components/OurTeamSection';
import OurValuesSection from '@/app/about/components/OurValuesSection';
import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'About',
	// description: 'Generated by create next app',
	keywords: ['About', 'React', 'JavaScript'],
};

const AboutPage = (): React.JSX.Element => {
	return (
		<main className="z-0 mt-[5rem] h-auto w-full">
			<HeroHeading heading={'About Us'} />
			<HeroSection />
			<OurServicesSection />
			<OurValuesSection />
			<OurTeamSection />
			<FAQ />
		</main>
	);
};

export default AboutPage;
