import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Projects - Shoolin Construction',
	description: 'Generated by create next app',
};

const ProjectsLayout = ({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element => {
	return <section>{children}</section>;
};
export default ProjectsLayout;
