import HeroHeading from '@/components/HeroHeading';
import Footer from '@/components/Footer';
import React from 'react';
import { Metadata } from 'next';
import SectionHeading from '@/components/SectionHeading';
import { client } from '@/sanity/lib/client';
import { PROJECTS_QUERY } from '@/sanity/lib/queries';
import Projects from '@/components/Projects';
import { SanityImageObject } from '@sanity/image-url/lib/types/types';
import { Project } from '@/sanity/types/sanity.types';

export const metadata: Metadata = {
	title: 'Projects - Shoolin Construction',
	description: 'Generated by create next app',
};

const ProjectPage = async (): Promise<React.JSX.Element> => {
	const projects = await client.fetch<Project[]>(PROJECTS_QUERY);
	console.log('Projects====>', projects);
	return (
		<main className="mt-[5rem] h-auto w-full">
			<HeroHeading heading={'Our Projects'} subHeading={'Projects'} />
			<section className="h-auto w-full  ">
				<section className="mx-auto h-auto w-full max-w-7xl space-y-20 px-5 pb-40 xl:px-0">
					<section className="flex w-full flex-col">
						<SectionHeading
							mainTitle={'Current Projects'}
							subTitle={'Ongoing'}
						/>
						<section className=" grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3">
							{projects.map((project) => {
								return project.status === 'under_construction' ||
									project.status === 'completed' ? (
									<Projects
										key={project._id}
										slug={project.slug}
										image={project.master_layout_plan as SanityImageObject}
										status={project.status}
										name={project.title}
										description={project.description}
										// address={item.address}
									/>
								) : (
									<></>
								);
							})}
						</section>
					</section>
					<section className="flex w-full flex-col">
						<SectionHeading mainTitle={'Complete Projects'} subTitle={'Done'} />
						<section className=" grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-3">
							{projects.map((project) =>
								project.status === 'completed' ? (
									<Projects
										key={project._id}
										slug={project.slug}
										image={project.master_layout_plan as SanityImageObject}
										status={project.status}
										name={project.title}
										description={project.description}
										// address={item.address}
									/>
								) : (
									<></>
								)
							)}
						</section>
					</section>
				</section>
			</section>
			<Footer />
		</main>
	);
};

export default ProjectPage;
