import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Contact - Shoolin Construction',
	description: 'Generated by create next app',
};

const ContactLayout = ({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element => {
	return (
		<section>
			{children}
			<Toaster />
		</section>
	);
};

export default ContactLayout;
