import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title:
		'Shoolin Construction | Provides Commercial & Residential Real estate Property-Buy-Sell-Rent Comapany',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
