import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Privacy Policy - Shoolin Construction',
	description: 'Generated by create next app',
};

const PrivacyPage = (): JSX.Element => {
	return <main className="z-0 mt-[5rem] h-auto w-full">Privacy Policy</main>;
};

export default PrivacyPage;
